# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
#rdiscount:
 # extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sundeepkamath.github.io
baseurl: /
title: Sundeep Kamath's coding blog
author: Sundeep Kamath
description: Personal blog #and resume
avatar: profile.png
email: sundeep.g.kamath@gmail.com
github: sundeepkamath # username
twitter: sundeepkamath
linkedin: sundeepgkamath
stackoverflow: users/77286/sundeep   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
